/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manually creating our sidebar for docs & API reference
  docs: [
    'intro',
    'getstarted',
    {
      type: 'category',
      label: 'Fixie Fundamentals',
      items: [
        'fundamentals/architecture',
        'fundamentals/agentlifecycle',
        {
          type: 'category',
          label: 'Common Use Cases',
          items: [
            'fundamentals/document-qa',
            'fundamentals/langchain',
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Building Fixie Agents',
      link: {type: 'doc', id: 'buildingagents/buildingfixieagents'},
      items: [
        'buildingagents/agent-quickstart',
        'buildingagents/python-quickstart',
        'buildingagents/agent-api',
        'buildingagents/agent-protocol',
      ]
    },
    {
      type: 'category',
      label: 'API Clients',
      link: {type: 'doc', id: 'apiclients/api-clients'},
      items: [
        'apiclients/python-sdk',
        'apiclients/python-client-api',
        'apiclients/python-agent-api',
        'apiclients/cli',
      ]
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'apireference/apireference'},
      items: [
        'apireference/graphql',
      ]
    },

    // 'buildingfixieagents',
    'tutorials',
    'troubleshooting',
  ],
};

module.exports = sidebars;
